name: "Update Upstream"

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/update.yaml@7b3d415a47bf67024079ff9d9a0cbb96d7067276
    secrets: inherit
